# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Game Systems
  items:
    - label: 'Leveling'
      link: '/systems/leveling'
    - label: 'Classes'
      link: '/systems/classes'
- label: Documentation
  items:
    - label: 'Loot tables'
      link: '/mob-list'
    - label: 'Spells'
      link: '/spells'
